### ISSUE TITLE
Visuals of the plugin

### ISSUE THREAD

**Issue by Bandgren** [deutschebank/backstage-plugins#1]
Hi! 

From reading it looks like something we might be interested in! But would it be possible to show some images of the fronted aspects to get a more visual grasp of the plugin and its possibilities? 

Br Bandgren

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@Bandgren : Thanks for reporting this. Yes, we will do another release this week to add the images of the frontend aspects of the plugin. Will let you know once done over this thread

**Comment by Bandgren** [comment]
@shanthisagar-dhanya-kumar-db that sounds perfect! Thank you!

**Comment by shanthisagar-dhanya-kumar-db** [comment]
@Bandgren : I have added the image now.

**Comment by shanthisagar-dhanya-kumar-db** [comment]
Images are added
